apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-upload-pvc
  namespace: nexus-azure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nexus-upload-pv
  storageClassName: azure-blob-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-processing-pvc
  namespace: nexus-azure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nexus-processing-pv
  storageClassName: azure-blob-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-extracted-pvc
  namespace: nexus-azure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nexus-extracted-pv
  storageClassName: azure-blob-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-models-pvc
  namespace: nexus-azure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nexus-models-pv
  storageClassName: azure-blob-storage 