apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob-storage
provisioner: blob.csi.azure.com
parameters:
  storageAccount: nexusazurestorage
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate