# aktus-gmp-embedding/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-embedding
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-embedding-service
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: aktus-embedding-service
        azure-extensions-usage-release-identifier: "{{ .Release.Name }}"
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: nexus-primary-cluster-sa
      nodeSelector:
        agentpool: computepool
      containers:
        - name: aktus-embedding-service
          image: "{{ .Values.global.azure.images.aktusEmbedding.registry }}/{{ .Values.global.azure.images.aktusEmbedding.image }}:{{ .Values.global.azure.images.aktusEmbedding.tag }}"
          imagePullPolicy: "{{ .Values.aktusEmbedding.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.aktusEmbedding.port }}
              name: http
          env:
            - name: SUMMARIZATION_NUM_PAGES
              value: "{{ .Values.aktusEmbedding.app.summarizationNumPages }}"
            - name: CHUNKING_CONCURRENCY
              value: "{{ .Values.aktusEmbedding.app.chunkingConcurrency }}"
            - name: CHUNKING_BATCH_SIZE
              value: "{{ .Values.aktusEmbedding.app.chunkingBatchSize }}"
            - name: EMBEDDING_BATCH_SIZE
              value: "{{ .Values.aktusEmbedding.app.embeddingBatchSize }}"
            - name: USERNAME
              value: "{{ .Values.aktusEmbedding.auth.username }}"
            - name: PASSWORD
              value: "{{ .Values.aktusEmbedding.auth.password }}"
            - name: HOST_ADDRESS
              value: "{{ .Values.aktusEmbedding.uvicorn.host }}"
            - name: HOST_PORT
              value: "{{ .Values.aktusEmbedding.uvicorn.port }}"
            - name: UVICORN_LOG_LEVEL
              value: "{{ .Values.aktusEmbedding.uvicorn.logLevel }}"
            - name: UVICORN_TIMEOUT_KEEPALIVE
              value: "{{ .Values.aktusEmbedding.uvicorn.timeoutKeepalive }}"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aktus-openai-secret
                  key: aktus-openai-key
            - name: SERVICE_OCR_ENDPOINT
              value: "{{ .Values.aktusEmbedding.mdiService.endpoint }}"
            - name: EXTRACTED_DATA_DIR
              value: "{{ .Values.aktusEmbedding.paths.extractedData }}"
            - name: DOC_UPLOAD_DIR
              value: "{{ .Values.aktusEmbedding.paths.docUpload }}"
            - name: DB_MANAGER_HOST
              value: "{{ .Values.aktusEmbedding.dbManager.host }}"
            - name: QDRANT_URL
              value: "{{ .Values.aktusEmbedding.endpoints.qdrant }}"
            - name: VECTOR_DB_TYPE
              value: "{{ .Values.aktusEmbedding.endpoints.vectorDbType }}"
            - name: ENV
              value: "{{ .Values.aktusEmbedding.app.env }}"
            - name: COMMUNITY_REPORT_GRAPH_PROMPT_PATH
              value: "{{ .Values.aktusEmbedding.prompts.communityReportGraph }}"
            - name: EXTRACT_CLAIMS_PROMPT_PATH
              value: "{{ .Values.aktusEmbedding.prompts.extractClaims }}"
            - name: PROJECT_ROOT_PATH
              value: "{{ .Values.aktusEmbedding.prompts.projectRoot }}"
          volumeMounts:
            - name: extracted-data
              mountPath: {{ .Values.aktusEmbedding.paths.extractedData }}
            - name: document-upload
              mountPath: {{ .Values.aktusEmbedding.paths.docUpload }}
            - name: doc-processing
              mountPath: {{ .Values.aktusEmbedding.paths.docProcessing }}
            - name: nomic-dir
              mountPath: /root/.nomic
            - name: ephemeral
              mountPath: "/tmp"
            - name: graphrag-data-pvc
              mountPath: {{ .Values.aktusEmbedding.paths.graphragData }}
          resources:
            {{- toYaml .Values.aktusEmbedding.resources | nindent 12 }}

      volumes:
        - name: extracted-data
          persistentVolumeClaim:
            claimName: nexus-extracted-pvc
        - name: document-upload
          persistentVolumeClaim:
            claimName: nexus-upload-pvc
        - name: doc-processing
          persistentVolumeClaim:
            claimName: nexus-processing-pvc
        - name: nomic-dir
          emptyDir: {}
        - name: ephemeral
          emptyDir:
            sizeLimit: 5Gi
        - name: graphrag-data-pvc
          persistentVolumeClaim:
            claimName: graphrag-data-pvc
            readOnly: false