# charts/rabbitmq/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        azure-extensions-usage-release-identifier: "{{ .Release.Name }}"
    spec:
      nodeSelector:
        agentpool: standardpool
      containers:
        - name: rabbitmq
          image: "{{ .Values.global.azure.images.rabbitmq.registry }}/{{ .Values.global.azure.images.rabbitmq.image }}:{{ .Values.global.azure.images.rabbitmq.tag }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.rabbitmq.managementPort }}
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.username }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: rabbitmq-definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
          resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "1000m"
                memory: "2Gi"
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
        - name: rabbitmq-config
          configMap:
            name: {{ .Release.Name }}-rabbitmq-config
        - name: rabbitmq-definitions
          configMap:
            name: {{ .Release.Name }}-rabbitmq-definitions