apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.global.azure.storage.account | b64enc }}
  azurestorageaccountkey: {{ .Values.global.azure.storage.key | default "" | b64enc }} 