apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob-fuse
provisioner: blob.csi.azure.com
parameters:
  storageAccount: {{ .Values.global.azure.storage.account }}
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate 