apiVersion: v1
kind: Service
metadata:
  name: aktus-knowledge-assistant
  labels:
    app: aktus-knowledge-assistant-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aktus-knowledge-assistant-service