# charts/aktus-postgres-service/values.yaml
aktusPostgres:
  image: postgres:13.16
  username: root
  password: secret
  database: root
  port: 5432
  persistence:
    enabled: true
    size: 500Gi
    storageClass: managed-csi
    accessMode: ReadWriteOnce
    subPath: postgresql-data
  initScripts:
    enabled: true
    configMap: postgres-init
  resources:
    requests:
      cpu: "2000m"
      memory: "8Gi"
    limits:
      cpu: "3500m"
      memory: "14Gi"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10

serviceAccount:
  name: "nexus-primary-cluster-sa"

nodeSelector:
  agentpool: standardpool