# aktus-gmp-db-manager/values.yaml
aktusDatabase:
  image: "{{ .Values.global.azure.images.aktusDatabase.registry }}/{{ .Values.global.azure.images.aktusDatabase.image }}:{{ .Values.global.azure.images.aktusDatabase.tag }}"
  imagePullPolicy: Always
  port: 80
  
  # Application configuration
  app:
    logLevel: "DEBUG"
    
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
      
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      
  dbConfig:
    username: root
    password: secret
    host: aktus-postgres
    port: 5432
    dbName: root

serviceAccount:
  name: "nexus-primary-cluster-sa"

nodeSelector:
  agentpool: standardpool