aktusResearch:
  image: aktusmarketplace.azurecr.io/aktus-research:latest
  imagePullPolicy: Always
  port: 8080
  service:
    type: ClusterIP
    port: 8080
  
  auth:
    username: "guest"
    password: "guest"
  
  uvicorn:
    host: "0.0.0.0"
    port: "8080"
    logLevel: "debug"
    timeoutKeepAlive: "3600"
  
  anyscale:
    apiBase: "https://api.endpoints.anyscale.com/v1"
  
  modelInference:
    address: ""
  
  embeddingService:
    host: "aktus-embedding:8080"
  
  paths:
    docUpload: "/document_upload"
    docImage: "/doc_processing" 
    extractedData: "/extracted_data"
  
  # Azure Blob Storage configuration
  storage:
    documentUpload:
      storageAccount: "nexusazurestorage"
      containerName: "nexus-upload"
      readOnly: false
    docProcessing:
      storageAccount: "nexusazurestorage"
      containerName: "nexus-processing"
      readOnly: false
    extractedData:
      storageAccount: "nexusazurestorage"
      containerName: "nexus-extracted"
      readOnly: false
  
  resources:
    requests:
      cpu: "4000m"
      memory: "16Gi"

healthcheck:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 60
  failureThreshold: 20

serviceAccount:
  name: "nexus-primary-cluster-sa"

nodeSelector:
  agentpool: standardpool