apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-storage
  labels:
    app: aktus-postgres-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "{{ .Values.aktusPostgres.persistence.storageClass }}" 