apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-database-service
  template:
    metadata:
      labels:
        app: aktus-database-service
        azure-extensions-usage-release-identifier: "{{ .Release.Name }}"
    spec:
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      nodeSelector:
        agentpool: standardpool
      containers:
        - name: aktus-database-service
          image: "{{ .Values.global.azure.images.aktusDatabase.registry }}/{{ .Values.global.azure.images.aktusDatabase.image }}:{{ .Values.global.azure.images.aktusDatabase.tag }}"
          imagePullPolicy: "{{ .Values.aktusDatabase.imagePullPolicy }}"
          ports:
            - containerPort: {{ .Values.aktusDatabase.port }}
              name: http
          env:
            - name: DB_CONNECTION_USERNAME
              value: "{{ .Values.aktusDatabase.dbConfig.username }}"
            - name: DB_CONNECTION_PASSWORD
              value: "{{ .Values.aktusDatabase.dbConfig.password }}"
            - name: DB_CONNECTION_HOST
              value: "{{ .Values.aktusDatabase.dbConfig.host }}"
            - name: DB_CONNECTION_PORT
              value: "{{ .Values.aktusDatabase.dbConfig.port | toString }}"
            - name: DB_CONNECTION_DB_NAME
              value: "{{ .Values.aktusDatabase.dbConfig.dbName }}"
            - name: LOG_LEVEL
              value: "{{ .Values.aktusDatabase.app.logLevel }}"
          resources:
            {{- toYaml .Values.aktusDatabase.resources | nindent 12 }}