apiVersion: apps/v1
kind: Deployment
metadata:
  name: aktus-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aktus-database-service
  template:
    metadata:
      labels:
        app: aktus-database-service
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: aktus-database-service
          image: {{ .Values.aktusDatabase.image }}
          imagePullPolicy: {{ .Values.aktusDatabase.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.aktusDatabase.port }}
              name: http
          env:
            - name: DB_CONNECTION_USERNAME
              value: "{{ .Values.aktusDatabase.dbConfig.username }}"
            - name: DB_CONNECTION_PASSWORD
              value: "{{ .Values.aktusDatabase.dbConfig.password }}"
            - name: DB_CONNECTION_HOST
              value: "{{ .Values.aktusDatabase.dbConfig.host }}"
            - name: DB_CONNECTION_PORT
              value: "{{ .Values.aktusDatabase.dbConfig.port | toString }}"
            - name: DB_CONNECTION_DB_NAME
              value: "{{ .Values.aktusDatabase.dbConfig.dbName }}"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            {{- toYaml .Values.aktusDatabase.resources | nindent 12 }}