# charts/aktus-gmp-db-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aktus-database
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app: aktus-database-service