# charts/rabbitmq/values.yaml
rabbitmq:
  image: "{{ .Values.global.azure.images.rabbitmq.registry }}/{{ .Values.global.azure.images.rabbitmq.image }}:{{ .Values.global.azure.images.rabbitmq.tag }}"
  username: guest
  password: guest
  managementPort: 15672
  amqpPort: 5672
  definitions:
    enabled: true
    configMap: rabbitmq-definitions

nodeSelector:
  agentpool: standardpool